### PR TITLE
feat: Allow configure auth

### PR DESCRIPTION
**Pull request by paragor**
This PR need to add PR to https://github.com/Ferlab-Ste-Justine/terraform-provider-etcd/pull/2 for support Auth configure.

### CODE REVIEW

**Comment by paragor** [comment]
@Magnitus-

**Comment by paragor** [comment]
@Magnitus-

**Comment by Magnitus-** [comment]
Apologies for the delays. Busy week. I'll take a peek a it.

**Comment by Magnitus-** [comment]
@paragor Ok, sorry that it took so long. I just validated the changes locally and everything looks good.

Only feedback I have for this one is perhaps rename the methods to:
```
GetAuthStatus
SetAuthStatus
```

For the first one, its a departure from the underlying etcd client v3, but consistent with how methods are named in this sdk in other places.

For the suggested name of the set method, I just think it has a nice symmetry with the get method that makes it easier to wrap your head around.

Let me know what you think. 

Otherwise, once we get that merged, I'll do a release of the sdk and update it in the terraform provider (assuming this is merged by tomorrow night, I'll do it tomorrow as I have a day off tomorrow). From there, I'll look at your PR in the terraform provider.

**Review by Magnitus- — APPROVED** [review]
@paragor I'll merge this and then do the name adjustments I suggested above in a separate commit.

I'll work some more on the sdk and I don't want this PR to fall by the wayside.

If you find that you disagree with the change, I'll be available for further discussion on that topic.

**Comment by paragor** [comment]
Sorry, i was sick

It will be released?

wanna use in https://github.com/Ferlab-Ste-Justine/terraform-provider-etcd/pull/2/files

**Comment by Magnitus-** [comment]
> Sorry, i was sick
> 
> It will be released?
> 
> wanna use in https://github.com/Ferlab-Ste-Justine/terraform-provider-etcd/pull/2/files

Sure, I still have some changes I want to do with the sdk, but nothing that will immediately break the api contract, so I guess I can do a release in the state it is in right now and update the etcd provider.

**Pull request merged**
