### PR TITLE
fix: Allow auth without TLS

### PR DESCRIPTION
**Pull request by paragor**

### CODE REVIEW

**Comment by paragor** [comment]
@Magnitus- ping

**Review by Magnitus- — APPROVED** [review]
LGTM

**Comment by Magnitus-** [comment]
@paragor Merging seems to be silently failing even though everything is green. I'm not sure if it is a transient problem with github or something with our repo/org configurations. I'll look around.

**Comment by paragor** [comment]
@Magnitus- github is down :(

https://www.githubstatus.com/

**Comment by Magnitus-** [comment]
@paragor Ok. We'll get it merged once they are operational again. 

I'll look at the rest of your PRs within the next couple of days. I'll do it one PR at a time.

**Pull request merged**
